# Generated by Django 5.2.6 on 2025-10-29 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_movielist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image_card',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='image_cover',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='video',
        ),
        migrations.AddField(
            model_name='movie',
            name='image_card_url',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='movie',
            name='image_cover_url',
            field=models.URLField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='movie',
            name='video_url',
            field=models.URLField(default='', max_length=500),
        ),
    ]
